### ISSUE TITLE
Error when creating Azure AD App registration

### ISSUE THREAD

**Issue by krwilson-msft** [OfficeDev/microsoft-teams-apps-request-a-guest#4]
The password generated for the AD App registration did not meet complexity requirements. 

Line 298 on the deployment script. 

 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/80262713/126289124-3baeca7a-1065-4182-968e-ab505c98e001.png)

**Comment by tobiheim** [comment]
Problem is fixed. Special characters are now included.
