### ISSUE TITLE
Problem in Power Apps Formulas

### ISSUE THREAD

**Issue by Sara8789** [OfficeDev/microsoft-teams-apps-request-a-guest#6]
We have a problem with some formulas in powerapps. It doesn't recognize some formulas. How can we modify them?
"My requests" page doesn't work and in the "Approve requests" page we can't see who submitted the form.
Also, we don't receive any adaptive card notification, neither Requests and approval notifications are sent to the approval mailbox.
No guest user account is created, evenf if the status of the Domain check is approved.

Could you help us solve these problems?

![InkedMicrosoftTeams-image_LI](https://user-images.githubusercontent.com/92574462/137463938-21eb843a-b63c-4786-8bbb-e7a0d664f9a9.jpg)

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/92574462/137463984-1a63502c-80e8-4be2-ac53-4f3603f957e1.png)

**Comment by krwilson-msft** [comment]
Hi, Can you check in the SharePoint list "Guests" whether the "Created By" field is populated for that request? These attributes are taken from the SP list once a Guest Request has been submitted.

**Comment by Sara8789** [comment]
Thank you! Resolved! ;)
