### ISSUE TITLE
unrecognized arguments: --password

### ISSUE THREAD

**Issue by wallandall** [OfficeDev/microsoft-teams-apps-request-a-guest#8]
When installing the application I get an error: unrecognized arguments: --password ?
When reviewing the MS documentation --password is not a valid parameter .
The line where i get the error is line 296: 
az ad app create --display-name $appName --required-resource-accesses $manifestPath --password $appSecret --end-date '2299-12-31T11:59:59+00:00' |ConvertFrom-Json # TODO Create Time automatically

Is there a way to correct this error?

**Comment by tobiheim** [comment]
Thanks for the feedback @wallandall! The deployment script will be updated according to the updated **az ad app** command reference.

**Comment by tobiheim** [comment]
App registration creation is now updated.
